CREATE TABLE users(
	id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	user VARCHAR(50) NOT NULL,
	email VARCHAR(50) NOT NULL,
	password VARCHAR(70) NOT NULL
);

CREATE TABLE products(
	id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	name VARCHAR(50) NOT NULL,
	category VARCHAR(50) NOT NULL,
	price INT NOT NULL,
	image VARCHAR(50) NOT NULL
);


