module.exports.data = [
    {
        name: 'Brownie A',
        category: 'Brownies',
        price: 450,
        img: "https://i.ibb.co/qFmfLVP/brownie.jpg",
    },
    {
        name: 'Brownie B',
        category: 'Brownies',
        price: 450,
        img: "https://i.ibb.co/qFmfLVP/brownie.jpg",
    },
    {
        name: 'Brownie C',
        category: 'Brownies',
        price: 450,
        img: "https://i.ibb.co/qFmfLVP/brownie.jpg",
    },
    {
        name: 'Brownie D',
        category: 'Brownies',
        price: 450,
        img: "https://i.ibb.co/qFmfLVP/brownie.jpg",
    },
    {
        name: 'Torta A',
        category: 'Tortas',
        price: 850,
        img: "https://i.ibb.co/qy73L7Z/torta.jpg",
    },
    {
        name: 'Torta B',
        category: 'Tortas',
        price: 850,
        img: "https://i.ibb.co/qy73L7Z/torta.jpg",
    },
    {
        name: 'Torta C',
        category: 'Tortas',
        price: 850,
        img: "https://i.ibb.co/qy73L7Z/torta.jpg",
    },
    {
        name: 'Torta D',
        category: 'Tortas',
        price: 850,
        img: "https://i.ibb.co/qy73L7Z/torta.jpg",
    },
    {
        name: 'Torta E',
        category: 'Tortas',
        price: 850,
        img: "https://i.ibb.co/qy73L7Z/torta.jpg",
    },
    {
        name: 'Torta F',
        category: 'Tortas',
        price: 850,
        img: "https://i.ibb.co/qy73L7Z/torta.jpg",
    },
    {
        name: 'Masita A',
        category: 'Masitas',
        price: 600,
        img: "https://i.ibb.co/QbVwSLD/masitas.jpg",
    },
    {
        name: 'Masita B',
        category: 'Masitas',
        price: 600,
        img: "https://i.ibb.co/QbVwSLD/masitas.jpg",
    },
    {
        name: 'Tarta A',
        category: 'Tartas',
        price: 1250,
        img: "https://i.ibb.co/54Z2DpR/pie.jpg",
    },
    {
        name: 'Tarta B',
        category: 'Tartas',
        price: 1250,
        img: "https://i.ibb.co/54Z2DpR/pie.jpg",
    },
    {
        name: 'Tarta C',
        category: 'Tartas',
        price: 1250,
        img: "https://i.ibb.co/54Z2DpR/pie.jpg",
    },
    {
        name: 'Tarta D',
        category: 'Tartas',
        price: 1250,
        img: "https://i.ibb.co/54Z2DpR/pie.jpg",
    },
    {
        name: 'Tarta E',
        category: 'Tartas',
        price: 1250,
        img: "https://i.ibb.co/54Z2DpR/pie.jpg",
    },
    {
        name: 'Churros x12',
        category: 'Churros',
        price: 800,
        img: "https://i.ibb.co/tJQXqz3/churros.jpg",
    },
    {
        name: 'Churros x6',
        category: 'Churros',
        price: 450,
        img: "https://i.ibb.co/tJQXqz3/churros.jpg",
    },
    {
        name: 'Muffin A',
        category: 'Muffins',
        price: 350,
        img: "https://i.ibb.co/4mhn5rR/muffin.jpg",
    },
    {
        name: 'Muffin B',
        category: 'Muffins',
        price: 350,
        img: "https://i.ibb.co/4mhn5rR/muffin.jpg",
    },
    {
        name: 'Muffin C',
        category: 'Muffins',
        price: 350,
        img: "https://i.ibb.co/4mhn5rR/muffin.jpg",
    },
    {
        name: 'Muffin D',
        category: 'Muffins',
        price: 350,
        img: "https://i.ibb.co/4mhn5rR/muffin.jpg",
    },
    {
        name: 'Muffin E',
        category: 'Muffins',
        price: 350,
        img: "https://i.ibb.co/4mhn5rR/muffin.jpg",
    },
    {
        name: 'Muffin F',
        category: 'Muffins',
        price: 350,
        img: "https://i.ibb.co/4mhn5rR/muffin.jpg",
    },
    {
        name: 'Muffin G',
        category: 'Muffins',
        price: 350,
        img: "https://i.ibb.co/4mhn5rR/muffin.jpg",
    },
    {
        name: 'Budin A',
        category: 'Budines',
        price: 500,
        img: "https://i.ibb.co/GJSJDWL/budin.jpg",
    },
    {
        name: 'Budin B',
        category: 'Budines',
        price: 500,
        img: "https://i.ibb.co/GJSJDWL/budin.jpg",
    },
    {
        name: 'Cake (slice) A',
        category: 'Cakes',
        price: 600,
        img: "https://i.ibb.co/PZZ8pny/cake.jpg",
    },
    {
        name: 'Cake (slice) B',
        category: 'Cakes',
        price: 600,
        img: "https://i.ibb.co/PZZ8pny/cake.jpg",
    },
    {
        name: 'Cake (slice) C',
        category: 'Cakes',
        price: 600,
        img: "https://i.ibb.co/PZZ8pny/cake.jpg",
    },
    {
        name: 'Cake (slice) D',
        category: 'Cakes',
        price: 600,
        img: "https://i.ibb.co/PZZ8pny/cake.jpg",
    },
    {
        name: 'Café A',
        category: 'Café',
        price: 200,
        img: "https://i.ibb.co/YLQP25f/cafe.jpg",
    },
    {
        name: 'Café B',
        category: 'Café',
        price: 200,
        img: "https://i.ibb.co/YLQP25f/cafe.jpg",
    },
    {
        name: 'Café C',
        category: 'Café',
        price: 200,
        img: "https://i.ibb.co/YLQP25f/cafe.jpg",
    },
    {
        name: 'Té A',
        category: 'Té',
        price: 150,
        img: "https://i.ibb.co/X2Rwhnr/te.jpg",
    },
    {
        name: 'Té B',
        category: 'Té',
        price: 150,
        img: "https://i.ibb.co/X2Rwhnr/te.jpg",
    },
    {
        name: 'Chocolatada A',
        category: 'Chocolate',
        price: 150,
        img: "https://i.ibb.co/DYj9nm4/chocolatada.jpg",
    },
    {
        name: 'Chocolatada B',
        category: 'Chocolate',
        price: 150,
        img: "https://i.ibb.co/DYj9nm4/chocolatada.jpg",
    },
    {
        name: 'Café D',
        category: 'Café',
        price: 200,
        img: "https://i.ibb.co/YLQP25f/cafe.jpg",
    },
    {
        name: 'Café F',
        category: 'Café',
        price: 200,
        img: "https://i.ibb.co/YLQP25f/cafe.jpg",
    },
    {
        name: 'Café G',
        category: 'Café',
        price: 200,
        img: "https://i.ibb.co/YLQP25f/cafe.jpg",
    },
    
];
