INSERT INTO products(name, category, price, image)
VALUES('Brownie A', 'Brownies', 450, 'https://i.ibb.co/qFmfLVP/brownie.jpg'),
('Brownie B', 'Brownies', 450, 'https://i.ibb.co/qFmfLVP/brownie.jpg'),
('Brownie C', 'Brownies', 450, 'https://i.ibb.co/qFmfLVP/brownie.jpg'),
('Brownie D', 'Brownies', 450, 'https://i.ibb.co/qFmfLVP/brownie.jpg'),
('Torta A', 'Tortas', 850, 'https://i.ibb.co/qy73L7Z/torta.jpg'),
('Torta B', 'Tortas', 850, 'https://i.ibb.co/qy73L7Z/torta.jpg'),
('Torta C', 'Tortas', 850, 'https://i.ibb.co/qy73L7Z/torta.jpg'),
('Torta D', 'Tortas', 850, 'https://i.ibb.co/qy73L7Z/torta.jpg'),
('Torta E', 'Tortas', 850, 'https://i.ibb.co/qy73L7Z/torta.jpg'),
('Torta F', 'Tortas', 850, 'https://i.ibb.co/qy73L7Z/torta.jpg'),
('Masita A', 'Masitas',600, 'https://i.ibb.co/QbVwSLD/masitas.jpg'),
('Masita B', 'Masitas',600, 'https://i.ibb.co/QbVwSLD/masitas.jpg'),
('Tarta A', 'Tartas', 1250, 'https://i.ibb.co/54Z2DpR/pie.jpg'),
('Tarta B', 'Tartas', 1250, 'https://i.ibb.co/54Z2DpR/pie.jpg'),
('Tarta C', 'Tartas', 1250, 'https://i.ibb.co/54Z2DpR/pie.jpg'),
('Tarta D', 'Tartas', 1250, 'https://i.ibb.co/54Z2DpR/pie.jpg'),
('Tarta E', 'Tartas', 1250, 'https://i.ibb.co/54Z2DpR/pie.jpg'),
('Churros x12', 'Churros', 800, 'https://i.ibb.co/tJQXqz3/churros.jpg'),
('Churros x6', 'Churros', 450, 'https://i.ibb.co/tJQXqz3/churros.jpg'),
('Muffin A', 'Muffins', 350, 'https://i.ibb.co/4mhn5rR/muffin.jpg'),
('Muffin B', 'Muffins', 350, 'https://i.ibb.co/4mhn5rR/muffin.jpg'),
('Muffin C', 'Muffins', 350, 'https://i.ibb.co/4mhn5rR/muffin.jpg'),
('Muffin E', 'Muffins', 350, 'https://i.ibb.co/4mhn5rR/muffin.jpg'),
('Muffin F', 'Muffins', 350, 'https://i.ibb.co/4mhn5rR/muffin.jpg'),
('Muffin G', 'Muffins', 350, 'https://i.ibb.co/4mhn5rR/muffin.jpg'),
('Budin A', 'Budines', 500, 'https://i.ibb.co/GJSJDWL/budin.jpg'),
('Budin B', 'Budines', 500, 'https://i.ibb.co/GJSJDWL/budin.jpg'),
('Cake (slice) A', 'Cakes', 600, 'https://i.ibb.co/PZZ8pny/cake.jpg'),
('Cake (slice) B', 'Cakes', 600, 'https://i.ibb.co/PZZ8pny/cake.jpg'),
('Cake (slice) C', 'Cakes', 600, 'https://i.ibb.co/PZZ8pny/cake.jpg'),
('Cake (slice) D', 'Cakes', 600, 'https://i.ibb.co/PZZ8pny/cake.jpg'),
('Café A', 'Café', 200, 'https://i.ibb.co/YLQP25f/cafe.jpg'),
('Café B', 'Café', 200, 'https://i.ibb.co/YLQP25f/cafe.jpg'),
('Café C', 'Café', 200, 'https://i.ibb.co/YLQP25f/cafe.jpg'),
('Café D', 'Café', 200, 'https://i.ibb.co/YLQP25f/cafe.jpg'),
('Café E', 'Café', 200, 'https://i.ibb.co/YLQP25f/cafe.jpg'),
('Café F', 'Café', 200, 'https://i.ibb.co/YLQP25f/cafe.jpg'),
('Café G', 'Café', 200, 'https://i.ibb.co/YLQP25f/cafe.jpg'),
('Té A', 'Té', 150, 'https://i.ibb.co/X2Rwhnr/te.jpg'),
('Té B', 'Té', 150, 'https://i.ibb.co/X2Rwhnr/te.jpg'),
('Chocolatada A', 'Chocolate', 150, 'https://i.ibb.co/DYj9nm4/chocolatada.jpg'),
('Chocolatada B', 'Chocolate', 150, 'https://i.ibb.co/DYj9nm4/chocolatada.jpg')

